#!/usr/bin/env ruby
# frozen_string_literal: true
#
# gen_quality_dashboard.rb — regenerate QUALITY.md, the public dashboard
# (PRD-FIVE-NINES §8), FROM THE AUDIT LEDGERS. Nothing in QUALITY.md is
# hand-written: every number in it is derived here, and the file carries a
# GENERATED banner so a hand edit is visible in the next diff.
#
# WHY IT IS GENERATED. QUALITY.md is the trust wedge — the published, audited
# error rate is the one claim a competitor cannot copy without doing the work.
# A hand-maintained dashboard drifts silently from the ledgers it summarises,
# and the drift is invisible precisely because the document looks authoritative.
# On 2026-09-05 the file still published the pre-fix 83% baseline measured
# BEFORE every wave that fixed it. That is the failure this script prevents.
#
# THREE RULES IT ENFORCES MECHANICALLY:
#
#  1. §1.4's "what we will NOT claim" is EXTRACTED VERBATIM from
#     PRD-FIVE-NINES.md at generation time, never retyped. If the PRD's
#     wording changes, the dashboard follows it in the next regeneration; if
#     the section cannot be found, the script aborts rather than emit a
#     dashboard missing its own disclaimer.
#  2. A round whose ledgers fail I-11 (no verifier, or researcher == verifier)
#     CANNOT publish a rate. The round appears with its counts and the words
#     "researched, awaiting verification" — never a clean rate. An unverified
#     number is exactly the falsely-reviewed record class, one altitude up.
#  3. The aggregate is never printed without its per-claim table. The 2W
#     baseline earned that rule the hard way: its 80.6% blends an unbiased
#     measurement with one at 40% coverage, so RESULTS-s2w says "do not quote
#     that figure without the row below it". The generator emits them
#     together or not at all.
#
# Usage:
#   ruby scripts/gen_quality_dashboard.rb --tag=v2026.08.3           # write QUALITY.md
#   ruby scripts/gen_quality_dashboard.rb --tag=v2026.08.3 --check   # CI: fail if stale
#   ruby scripts/gen_quality_dashboard.rb --self-test

require "yaml"
require "json"
require "date"
require_relative "audit_aggregate"

module QualityDashboard
  ROOT = File.expand_path("..", __dir__)
  PRD = File.join(ROOT, "PRD-FIVE-NINES.md")
  OUT = File.join(ROOT, "QUALITY.md")
  ROUNDS = File.join(ROOT, "data", "review", "_rounds.yml")
  BANNER = "<!-- GENERATED by scripts/gen_quality_dashboard.rb from the audit ledgers. " \
           "Do not hand-edit: numbers here are derived, and a hand edit is a silent " \
           "divergence from the ledgers that back them. Regenerate instead. -->"

  module_function

  # Rule 1: the disclaimer is quoted from its source, not retyped here.
  def what_we_will_not_claim
    src = File.read(PRD)
    m = src.match(/^### 1\.4 What we will NOT claim\s*\n(.*?)(?=^##)/m)
    abort "PRD-FIVE-NINES.md §1.4 not found — refusing to emit a dashboard without its disclaimer" unless m
    body = m[1].strip
    abort "PRD-FIVE-NINES.md §1.4 is empty" if body.empty?
    body
  end

  def pct(x, dp = 2) = format("%.#{dp}f%%", x * 100)

  def claim_table(agg)
    rows = []
    rows << "| claim | n | correct | defective | source-gap | not-attempted | defect+unverif. | 95% CI (Clopper-Pearson) |"
    rows << "|---|---:|---:|---:|---:|---:|---:|---|"
    order = AuditAggregate::CLAIM_TYPES.select { |c| agg["by_claim"].key?(c) }
    (order + (agg["by_claim"].keys - order)).each do |k|
      r = agg["by_claim"][k]
      rows << format("| %s | %d | %d | %d | %d | %d | **%s** | %s–%s |",
                     k, r["n"], r["correct"], r["defective"], r["source_gap"],
                     r["not_attempted"], pct(r["defect_rate"]), pct(r["cp_lo"]), pct(r["cp_hi"]))
    end
    o = agg["overall"]
    rows << format("| **ALL** | %d | %d | %d | %d | %d | **%s** | %s–%s |",
                   o["n"], o["correct"], o["defective"], o["source_gap"],
                   o["not_attempted"], pct(o["defect_rate"]), pct(o["cp_lo"]), pct(o["cp_hi"]))
    rows.join("\n")
  end

  def bound_block(agg)
    s = agg["stratified"]
    return "- **Usage-weighted bound: NOT PUBLISHED this round.** " \
           "`catalog/meta/decile-mass.json` was absent from the pinned build, so the " \
           "weights the bound needs could not be read. The protocol requires them read, " \
           "never asserted (PRD-FIVE-NINES §1.3.2), so no weighted figure appears here." unless s && s["bound"]
    b = s["bound"]
    w = s["weights"]
    head = s["strata"]["head"]
    tail = s["strata"]["tail"]
    <<~MD.strip
      - **Usage-weighted 95% upper bound: #{pct(b['weighted_upper_bound'], 4)}**, with its
        three-strata arithmetic printed so it is recomputable from published artifacts:

        ```
        w_head · r_head  +  w_tail · r_tail
          w_head = #{format('%.6f', b['w_head'])}   (deciles 1–6, #{head['records']} sampled records, #{head['n']} claims)
          r_head ≤ #{format('%.6f', b['r_head_hi'])}   (95% Clopper-Pearson upper bound)
          w_tail = #{format('%.6f', b['w_tail'])}   (deciles 7–10 + none, #{tail['records']} sampled records, #{tail['n']} claims)
          r_tail ≤ #{format('%.6f', b['r_tail_hi'])}   (95% Clopper-Pearson upper bound)
          ⇒ bound = #{format('%.8f', b['weighted_upper_bound'])}
        ```

        Weights READ from `catalog/meta/decile-mass.json` in the pinned build
        (this half is #{pct(w['half_mass_share'], 4)} of total catalog registration mass;
        head/tail renormalised within the half). Detector coverage is deliberately NOT a
        stratum — it spans every decile and would push the weights past 1.
      - **Head and tail are reported separately and never blended**: head
        #{pct(head['defect_rate'])} defect+unverifiable over #{head['n']} claims
        (#{format('%.2f', head['claims_per_record'])} claims/record), tail
        #{pct(tail['defect_rate'])} over #{tail['n']} claims
        (#{format('%.2f', tail['claims_per_record'])} claims/record). §1.3.4: head records
        carry systematically more claims, so a record-level rate is not the same quantity
        in the two strata.
    MD
  end

  def audit_error_block(agg)
    a = agg["audit_error"]
    return "- The audit's own error rate: not computable (no verifier re-derivation recorded)." if a["corrects_sampled"].zero?
    "- **The audit's own error rates, published** (§5.2 — an instrument without a " \
      "published error rate is a marketing number): researcher miss rate on verifier-" \
      "sampled `correct` claims **#{pct(a['miss_rate'])}** " \
      "(#{a['corrects_missed']}/#{a['corrects_sampled']}, 95% CI #{pct(a['miss_cp_lo'])}–#{pct(a['miss_cp_hi'])}); " \
      "defect verdicts surviving adversarial re-derivation **#{pct(a['defect_hold_rate'])}** " \
      "(#{a['defect_verdicts_held']}/#{a['defect_verdicts_reviewed']}); class labels moved on " \
      "**#{pct(a['class_move_rate'])}** of confirmed defects (#{a['class_labels_moved']}) — " \
      "remedies differ by class, so a fix programme driven off unverified labels applies the " \
      "wrong remedy at that rate."
  end

  def half_section(title, agg, tag)
    unverified = !agg["i11"].empty?
    body = +"## Measured — #{title}, round #{tag}\n\n"
    if unverified
      body << "> **RESEARCHED, AWAITING VERIFICATION — no clean rate is published for this " \
              "half.** The ledgers exist and are readable, but I-11 (researcher ≠ verifier) is " \
              "not satisfied for every slice, and an unverified verdict must not be published as " \
              "a measurement:\n"
      agg["i11"].each { |p| body << ">   - #{p}\n" }
      body << ">\n> Counts only, for transparency: #{agg['resolved_count']} claims across " \
              "#{agg['by_claim'].values.sum { |r| r['n'] }} verdicts. The rate publishes when a " \
              "verifier signs.\n\n"
      return body
    end
    o = agg["overall"]
    body << "*Sample drawn by `scripts/audit_sample.rb` (seeded by tag, stratified per " \
            "§1.3), measured against the pinned build `#{Array(agg['build_pin']).first}`. " \
            "#{agg['meta']['slices'].size} independent researcher+verifier pairs; " \
            "researcher ≠ verifier on every slice. `unverifiable` counts AGAINST throughout.*\n\n"
    body << "- **Claim-level clean rate: #{pct(o['clean_rate'])}** " \
            "(#{o['correct']}/#{o['n']} claims). Defect+unverifiable " \
            "**#{pct(o['defect_rate'])}**, 95% Clopper-Pearson " \
            "**#{pct(o['cp_lo'])}–#{pct(o['cp_hi'])}**.\n"
    body << "- **Do not quote that aggregate without the table below it** — it pools claim " \
            "types with different coverage and different bias directions.\n"
    body << bound_block(agg) << "\n"
    body << audit_error_block(agg) << "\n\n"
    body << claim_table(agg) << "\n\n"
    unless agg["defect_classes"].empty?
      body << "Top defect classes (class as CONFIRMED BY THE VERIFIER, per protocol rule 3): "
      body << agg["defect_classes"].first(8).map { |c, n| "`#{c}` ×#{n}" }.join(" · ")
      body << "\n\n"
    end
    body
  end

  def rounds_record
    File.exist?(ROUNDS) ? (YAML.safe_load_file(ROUNDS, permitted_classes: [Date]) || {}) : {}
  end

  # The numeric block RESULTS.md embeds. RESULTS carries narrative — findings,
  # new defect classes, limitations — which a script cannot write; but every
  # NUMBER in it comes from here, so the prose and the tables cannot drift
  # apart. Emitted with begin/end markers so `--check` can verify the embedded
  # copy still matches the ledgers.
  RESULTS_BEGIN = "<!-- BEGIN GENERATED NUMBERS — scripts/gen_quality_dashboard.rb --results=%s -->"
  RESULTS_END = "<!-- END GENERATED NUMBERS -->"

  def results_block(agg)
    o = agg["overall"]
    b = +""
    b << format(RESULTS_BEGIN, agg["half"]) << "\n\n"
    if agg["i11"].empty?
      b << "**Claim-level clean rate: #{pct(o['clean_rate'])}** — #{o['correct']} correct / " \
           "#{o['defective']} defective / #{o['source_gap']} source-gap / " \
           "#{o['not_attempted']} not-attempted of #{o['n']} claims. " \
           "**Defect+unverifiable #{pct(o['defect_rate'])}, 95% Clopper-Pearson " \
           "#{pct(o['cp_lo'])}–#{pct(o['cp_hi'])}.**\n\n" \
           "*Do not quote that aggregate without the table below it.* It pools claim types " \
           "whose coverage and bias directions differ.\n\n"
    else
      b << "**No clean rate is published for this half.** I-11 is unsatisfied:\n\n"
      agg["i11"].each { |p| b << "- #{p}\n" }
      b << "\n"
    end
    b << claim_table(agg) << "\n\n"
    if (s = agg["stratified"]) && s["strata"]
      b << "### Per stratum (head = deciles 1–6, tail = 7–10 + none; never blended)\n\n"
      b << "| stratum | records | claims | claims/record | record-level defect rate | claim-level defect+unverif. | 95% CI |\n"
      b << "|---|---:|---:|---:|---:|---:|---|\n"
      %w[head tail].each do |name|
        r = s["strata"][name]
        next unless r
        b << format("| %s | %d | %d | %.2f | %s | %s | %s–%s |\n", name, r["records"], r["n"],
                    r["claims_per_record"], pct(r["record_rate"]), pct(r["defect_rate"]),
                    pct(r["cp_lo"]), pct(r["cp_hi"]))
      end
      b << "\n§1.3.4: head records carry systematically more claims than tail records, so the " \
           "record-level rates in this table are NOT like-for-like across strata. The " \
           "claim-level rates are.\n\n"
    end
    b << bound_block(agg) << "\n\n"
    b << audit_error_block(agg) << "\n\n"
    unless agg["defect_classes"].empty?
      b << "### Defect classes (as CONFIRMED BY THE VERIFIER — protocol rule 3)\n\n"
      b << "| class | confirmed defects |\n|---|---:|\n"
      agg["defect_classes"].each { |c, n| b << "| `#{c}` | #{n} |\n" }
      b << "\n"
    end
    b << RESULTS_END << "\n"
    b
  end

  def comparison_block(tag, aggs, prior)
    return "" if prior.nil? || prior.empty?
    lines = +"## Round-over-round — read the caveat before reading the arrows\n\n"
    lines << "The two rounds measured **different builds with different samples**, and the " \
             "catalog itself changed between them (folds, truncation-stub retirement, " \
             "junk-drop recovery). A movement here is evidence about the dataset only to the " \
             "extent the instrument stayed fixed, and it did not entirely: the sampler now " \
             "pins a build (protocol v1.2), `unverifiable` is now sub-typed (v1.3), and " \
             "verifiers now confirm class. Treat these as two measurements, not a time series.\n\n"
    lines << "| half | baseline #{prior['tag']} | this round #{tag} | note |\n|---|---|---|---|\n"
    %w[s4w s2w].each do |h|
      a = aggs[h]
      base = prior.dig("halves", h)
      next unless base
      now = a && a["i11"].empty? ? pct(a["overall"]["clean_rate"]) : "not published (unverified)"
      lines << "| #{h} | #{base['clean_rate']} | #{now} | #{base['caveat']} |\n"
    end
    lines << "\n"
    lines
  end

  def render(tag, aggs)
    prior = rounds_record["baseline"]
    published = aggs.values.any? { |a| a && a["i11"].empty? }
    out = +"#{BANNER}\n\n# QUALITY — the public dashboard (PRD-FIVE-NINES §8)\n\n"
    out << "*Generated #{Date.today.iso8601} from the verification ledgers under " \
           "`data/review/audit-#{tag}/`. Every number below is derived from those files by " \
           "`scripts/audit_aggregate.rb`; none is typed by hand. The caveats are part of the " \
           "product.*\n\n"
    out << "## Status: #{published ? 'INSTRUMENTED · ROUND 2 MEASURED ON A PINNED BUILD' : 'INSTRUMENTED · ROUND 2 RESEARCHED, AWAITING VERIFICATION'}\n\n"
    out << "| | |\n|---|---|\n"
    out << "| Program | PRD-FIVE-NINES.md (target: usage-weighted P(defective\\|touched) ≤ 1e-5) |\n"
    out << "| Instrument | seeded stratified audit (`scripts/audit_sample.rb`), researcher≠verifier, unverifiable-counts-against |\n"
    out << "| Latest round | **#{tag}, both halves** — 400 records/half, 4 independent researcher+verifier pairs each |\n"
    out << "| Protocol | `data/review/audit-PROTOCOL.md` v1.3 |\n\n"
    out << half_section("4W half (car/van/truck/bus)", aggs["s4w"], tag) if aggs["s4w"]
    out << half_section("2W half (motorcycle/moped)", aggs["s2w"], tag) if aggs["s2w"]
    out << comparison_block(tag, aggs, prior)
    out << "## What we will not claim (verbatim from PRD-FIVE-NINES §1.4)\n\n"
    out << what_we_will_not_claim << "\n\n"
    out << "## Detector suite (held at zero in CI, every build)\n\n"
    out << "duplicate-spellings · casing-contradictions · corporate-strings · " \
           "published-name-defects (with recorded verdicts) · curation lint (direction wars, " \
           "chains, shapes) · reachability · id-contract gates 1–7 + publication hysteresis · " \
           "enrich lint (incl. duplicate-insurance sweep).\n\n"
    out << "Detector coverage is not a stratum in the bound above: it applies to every decile, " \
           "so it reduces both `r_head` and `r_tail` and carries no weight of its own " \
           "(PRD-FIVE-NINES §1.3).\n"
    out
  end

  def self_test!
    # The disclaimer must be extractable and must be the PRD's own words.
    t = what_we_will_not_claim
    raise "disclaimer extraction empty" if t.empty?
    raise "disclaimer not verbatim" unless t.include?("Not uniform per-record five nines")
    raise "disclaimer picked up the next section" if t.include?("Workstream A")
    # Rule 2: an I-11-failing round must not print a rate.
    unverified = { "i11" => ["slice 1: no verifier signed"], "resolved_count" => 10,
                   "by_claim" => { "id" => { "n" => 10 } }, "meta" => { "slices" => {} },
                   "overall" => { "clean_rate" => 0.99, "n" => 10, "correct" => 10,
                                  "defective" => 0, "source_gap" => 0, "not_attempted" => 0,
                                  "defect_rate" => 0.0, "cp_lo" => 0.0, "cp_hi" => 0.3 } }
    sec = half_section("test half", unverified, "vTEST")
    raise "unverified round leaked a rate" if sec.include?("99.00%")
    raise "unverified round not labelled" unless sec.include?("AWAITING VERIFICATION")
    # Rule 3: a published half prints the table with the aggregate.
    verified = { "i11" => [], "resolved_count" => 10, "build_pin" => ["/tmp/b/out"],
                 "meta" => { "slices" => { "1" => {} } },
                 "by_claim" => { "id" => { "n" => 10, "correct" => 9, "defective" => 1,
                                           "source_gap" => 0, "not_attempted" => 0,
                                           "defect_rate" => 0.1, "cp_lo" => 0.0025,
                                           "cp_hi" => 0.4450 } },
                 "overall" => { "n" => 10, "correct" => 9, "defective" => 1, "source_gap" => 0,
                                "not_attempted" => 0, "clean_rate" => 0.9, "defect_rate" => 0.1,
                                "cp_lo" => 0.0025, "cp_hi" => 0.4450 },
                 "stratified" => nil, "audit_error" => { "corrects_sampled" => 0 },
                 "defect_classes" => { "D6" => 1 } }
    sec2 = half_section("test half", verified, "vTEST")
    raise "aggregate without its table" unless sec2.include?("| claim |") && sec2.include?("90.00%")
    raise "missing do-not-quote caveat" unless sec2.include?("without the table below it")
    # A round with no decile-mass says so instead of inventing a bound.
    raise "silent missing bound" unless sec2.include?("NOT PUBLISHED this round")
    puts "self-test: OK (disclaimer extracted verbatim from the PRD and bounded to its own " \
         "section; unverified rounds cannot print a rate; the aggregate never prints without " \
         "its per-claim table; a missing decile-mass artifact is stated, not silently skipped)"
  end
end

if $PROGRAM_NAME == __FILE__
  opts = {}
  ARGV.each do |a|
    case a
    when "--self-test" then QualityDashboard.self_test!; exit 0
    when "--check" then opts["check"] = true
    when /\A--results=(s4w|s2w)\z/ then opts["results"] = $1
    when /\A--tag=(.+)/ then opts["tag"] = $1
    else abort "unknown arg #{a}"
    end
  end
  abort "need --tag=<release tag> (or --self-test)" unless opts["tag"]
  if opts["results"]
    puts QualityDashboard.results_block(AuditAggregate.run(opts["tag"], opts["results"]))
    exit 0
  end
  aggs = {}
  %w[s4w s2w].each do |h|
    dir = File.join(QualityDashboard::ROOT, "data", "review", "audit-#{opts['tag']}", "ledger")
    next if Dir[File.join(dir, "researcher-#{h}-b*.yml")].empty?
    aggs[h] = AuditAggregate.run(opts["tag"], h)
  end
  abort "no ledgers found for #{opts['tag']} — nothing to generate from" if aggs.empty?
  rendered = QualityDashboard.render(opts["tag"], aggs)
  if opts["check"]
    current = File.exist?(QualityDashboard::OUT) ? File.read(QualityDashboard::OUT) : ""
    if current == rendered
      puts "QUALITY.md: up to date"
    else
      puts "QUALITY.md: STALE — regenerate with scripts/gen_quality_dashboard.rb --tag=#{opts['tag']}"
      exit 1
    end
  else
    File.write(QualityDashboard::OUT, rendered)
    puts "wrote #{QualityDashboard::OUT} (#{rendered.lines.size} lines) from #{aggs.keys.join(', ')} ledgers"
  end
end
