#!/usr/bin/env ruby
# frozen_string_literal: true
#
# gen_ownership.rb — (re)generate OWNERSHIP.yml from the published catalog.
#
# Curation is split between two maintainer sessions by MAKE, not by kind:
# one make = one owner, across all six kinds and all defect classes. The owner
# is the side that owns the make's DOMINANT kind by record count. This script
# computes that map so both sides read the same answer instead of each deriving
# it (we already derived it twice, from different rules, and got the same
# boundary — see NEGOTIATION.md Turn 1/2).
#
# Run after any release that adds makes:  ruby scripts/gen_ownership.rb
# Review the diff — a make changing owner mid-cleanup needs both sides to ack.

require "json"

ROOT   = File.expand_path("..", __dir__)
GROUPS = { "s4w" => %w[car van truck bus], "s2w" => %w[motorcycle moped] }.freeze
KINDS  = GROUPS.values.flatten.freeze

counts = {} # make_id => { kind => n }
names  = {} # make_id => display name
KINDS.each do |kind|
  JSON.parse(File.read(File.join(ROOT, "catalog", kind, "makes.json"))).each do |m|
    names[m["id"]] ||= m["name"]
  end
  JSON.parse(File.read(File.join(ROOT, "catalog", kind, "models.json"))).each do |m|
    (counts[m["make_id"]] ||= {})[kind] = (counts[m["make_id"]][kind] || 0) + 1
  end
end

# Ties are pinned BY AGREEMENT, never computed. Two makes tie on record count
# (adler 1|1, garia 2|2) and were arbitrated in NEGOTIATION.md Turn 1/2. They
# must be listed here because the computed fallback would depend on Hash
# insertion order from the catalog JSON — a future rebuild could silently flip
# a make's owner, which is precisely how two sessions end up both editing one
# make block (and one block silently disappearing: YAML keeps the last dup key).
# Any NEW tie must be added here explicitly, acked in NEGOTIATION.md first.
TIEBREAK = { "adler" => "s2w", "garia" => "s2w" }.freeze

owner_of = ->(id) do
  return TIEBREAK[id] if TIEBREAK.key?(id)
  by_kind = counts[id] || {}
  return "s4w" if by_kind.empty? # make with no models yet: default to 4W, harmless
  per_group = GROUPS.transform_values { |ks| ks.sum { |k| by_kind[k] || 0 } }
  return per_group.max_by { |_, n| n }.first if per_group.values.uniq.size > 1
  raise "tie on #{id} (#{per_group.inspect}) — add it to TIEBREAK after acking in NEGOTIATION.md"
end

owners = names.keys.sort.to_h { |id| [id, owner_of.(id)] }
split  = owners.each_with_object({ "s4w" => [], "s2w" => [] }) { |(id, o), h| h[o] << id }

# Makes with records in BOTH groups are the only ones where the rule arbitrates
# rather than merely reads off the kind — list them explicitly so a future
# recount can never silently flip one without showing up in review.
arbitrated = names.keys.select do |id|
  GROUPS.values.map { |ks| ks.sum { |k| (counts[id] || {})[k] || 0 } }.all?(&:positive?)
end.sort

lines = []
lines << "# OWNERSHIP.yml — GENERATED by scripts/gen_ownership.rb. Do not hand-edit."
lines << "#"
lines << "# One make = one owner, across all six kinds and all defect classes."
lines << "# Owner = the side owning the make's dominant kind by record count."
lines << "# s4w = car/van/truck/bus maintainer · s2w = motorcycle/moped maintainer"
lines << "#"
lines << "# Consequence to keep in mind: a make's owner curates it in EVERY kind, so"
lines << "# each side holds records inside the other's kinds. \"Done\" is therefore"
lines << "# defined per make-set, never per kind-set."
lines << "#"
lines << "# Totals: #{owners.size} makes — s4w #{split['s4w'].size}, s2w #{split['s2w'].size};"
lines << "#         #{arbitrated.size} makes span both kind groups (arbitrated below)."
lines << ""
lines << "kind_groups:"
GROUPS.each { |g, ks| lines << "  #{g}: [#{ks.join(', ')}]" }
lines << ""
lines << "# Makes with records in both kind groups — the arbitrated set. Counts are"
lines << "# 4W-records | 2W-records at generation time."
lines << "arbitrated:"
arbitrated.each do |id|
  f = GROUPS["s4w"].sum { |k| (counts[id] || {})[k] || 0 }
  t = GROUPS["s2w"].sum { |k| (counts[id] || {})[k] || 0 }
  lines << format("  %-22s %-4s  # %d | %d", "#{id}:", owners[id], f, t)
end
lines << ""
%w[s4w s2w].each do |g|
  lines << "#{g}:"
  split[g].each { |id| lines << "  - #{id}" }
  lines << ""
end

File.write(File.join(ROOT, "OWNERSHIP.yml"), lines.join("\n"))
puts "wrote OWNERSHIP.yml — #{owners.size} makes (s4w #{split['s4w'].size} / s2w #{split['s2w'].size}), " \
     "#{arbitrated.size} arbitrated"
puts "arbitrated: " + arbitrated.map { |id| "#{id}→#{owners[id]}" }.join(", ")
